// 매월 오리지널 곡(저작권 free)을 절차적으로 작곡해 generatedSongs.ts 로 출력.
//  - 월(month) 기준 결정론적 시드 → 같은 달은 항상 같은 곡(재실행해도 안정)
//  - 키 + 흔한 팝 코드진행 + 코드톤 중심 멜로디 생성
// 사용: node apps/games/scripts/composeSongs.mjs [YYYY-MM] [count]
import { writeFileSync, mkdirSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const here = dirname(fileURLToPath(import.meta.url))
const OUT = join(here, '..', 'src', 'data', 'generatedSongs.ts')

// ── 인자 ──
const now = new Date()
const month = process.argv[2] || `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
const count = Math.max(1, Math.min(10, Number(process.argv[3]) || 6))

// ── 시드 PRNG (mulberry32) ──
function hash(str) {
  let h = 1779033703 ^ str.length
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(h ^ str.charCodeAt(i), 3432918353)
    h = (h << 13) | (h >>> 19)
  }
  return h >>> 0
}
function mulberry32(a) {
  return function () {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

// ── 음악 자료 ──
const MAJOR = [0, 2, 4, 5, 7, 9, 11]
const MINOR = [0, 2, 3, 5, 7, 8, 10]
// 메이저 키 7화음 품질 (I ii iii IV V vi vii°)
const MAJ_QUAL = ['maj', 'min', 'min', 'maj', 'maj', 'min', 'min']
const MIN_QUAL = ['min', 'min', 'maj', 'min', 'min', 'maj', 'maj']
// 흔한 팝 진행 (스케일 도수, 0=I)
const PROGS = [
  [0, 4, 5, 3], // I V vi IV
  [5, 3, 0, 4], // vi IV I V
  [0, 5, 3, 4], // I vi IV V
  [3, 0, 4, 5], // IV I V vi
  [0, 3, 4, 0], // I IV V I
]
const TONICS = [60, 62, 64, 65, 67, 69] // C D E F G A (4옥타브)
const RHYTHMS = [
  [4, 4, 4, 4],
  [4, 2, 2, 4, 4],
  [2, 2, 4, 4, 4],
  [4, 4, 2, 2, 4],
  [2, 2, 2, 2, 4, 4],
  [4, 4, 4, 2, 2],
  [8, 4, 4],
  [2, 2, 2, 2, 2, 2, 2, 2],
]
const ADJ = ['네온', '별빛', '새벽', '폭주', '은하', '파스텔', '심야', '크리스탈', '오로라', '몽환', '코스믹', '하이퍼', '로파이', '선셋', '워터', '버블', '루프', '피크닉']
const NOUN = ['드라이브', '러시', '웨이브', '댄스', '하트비트', '점프', '시티', '로맨스', '판타지', '부스트', '멜로디', '스텝', '크루즈', '비트', '체이스', '글로우', '릴레이', '파라다이스']
const COLORS = ['#ff6b6b', '#f7d23e', '#54e07c', '#36cfe6', '#c069f0', '#5b8cf0', '#f5a347', '#ff8fab']

const rnd = mulberry32(hash(month))
const pick = (arr) => arr[Math.floor(rnd() * arr.length)]
const slug = (s) => s.replace(/\s+/g, '-')

function composeSong(i) {
  const tonic = pick(TONICS)
  const isMajor = rnd() < 0.62
  const scale = isMajor ? MAJOR : MINOR
  const quals = isMajor ? MAJ_QUAL : MIN_QUAL
  const prog = pick(PROGS)
  const bpm = 90 + Math.floor(rnd() * 64) // 90~153

  // 스케일 도수 → midi (한 옥타브 위 포함)
  const deg = (d) => {
    const oct = Math.floor(d / 7)
    const idx = ((d % 7) + 7) % 7
    return tonic + oct * 12 + scale[idx]
  }

  // 코드: [rootMidi, quality]
  const chords = prog.map((d) => [deg(d), quals[d % 7]])

  // 멜로디: 마디마다 코드톤 중심, 단계 진행
  const melody = []
  let cur = 7 // 으뜸음 한 옥타브 위에서 시작(도수)
  for (let bar = 0; bar < prog.length; bar++) {
    const chordDeg = prog[bar]
    const tones = [chordDeg, chordDeg + 2, chordDeg + 4].map((x) => x + 7) // 한 옥타브 위 코드톤(도수)
    const rhythm = pick(RHYTHMS)
    rhythm.forEach((len, k) => {
      const strong = k === 0 || len >= 4
      if (strong) {
        // 가까운 코드톤으로
        cur = tones.reduce((a, b) => (Math.abs(b - cur) < Math.abs(a - cur) ? b : a), tones[0])
      } else {
        cur += rnd() < 0.5 ? 1 : -1 // 경과음(단계)
      }
      cur = Math.max(5, Math.min(13, cur)) // 음역 제한
      melody.push([deg(cur), len])
    })
  }

  let title
  do {
    title = `${pick(ADJ)} ${pick(NOUN)}`
  } while (usedTitles.has(title))
  usedTitles.add(title)

  return {
    id: `${slug(title)}-${month}`,
    title,
    artist: '소리톡 오리지널',
    color: pick(COLORS),
    bpm,
    month,
    loops: 3,
    melody,
    chords,
  }
}

const usedTitles = new Set()
const songs = Array.from({ length: count }, (_, i) => composeSong(i))

const banner = `// AUTO-GENERATED by scripts/composeSongs.mjs — 직접 수정하지 마세요.
// month=${month} · ${songs.length}곡 · ${new Date().toISOString()}
`
const body = `import type { Song } from './songs'\n\nexport const GENERATED_SONGS: Song[] = ${JSON.stringify(
  songs,
  null,
  2,
)}\n`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, banner + body, 'utf8')
console.log(`✅ ${songs.length}곡 생성(${month}) → ${OUT}`)
songs.forEach((s) => console.log(`   · ${s.title} (${s.bpm}bpm, ${s.month})`))
